version: "3"

services:
  db:
    image: postgres:11.1
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ./entrypoint.sh
    depends_on:
      - db
