version: 2
jobs:
  checkout_code:
    working_directory: ~/app
    docker:
      - image: python:3.6.8
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  python_dependencies:
    working_directory: ~/app
    docker:
      - image: python:3.6.8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

  unit_tests:
    working_directory: ~/app
    docker:
      - image: python:3.6.8
      - image: postgres:11.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Unit Tests
          command: |
            pip install -r requirements.txt
            cd hello-django
            python manage.py test

workflows:
  version: 2
  pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - unit_tests:
          requires:
            - python_dependencies

          