version: 2
jobs:
  checkout_code:
    working_directory: ~/app
    docker:
      - image: python:3.6.8
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  python_dependencies:
    working_directory: ~/app
    docker:
      - image: python:3.6.8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

  unit_tests:
    working_directory: ~/app
    docker:
      - image: python:3.6.8
      - image: postgres:11.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Unit Tests
          command: |
            pip install -r requirements.txt
            cd hello-django
            export DATABASE_HOST=localhost
            python manage.py test
  build_docker_image:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6.8
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Stable Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/hello-django:stable .
            docker tag $DOCKER_USER/hello-django:stable $DOCKER_USER/hello-django:$CIRCLE_SHA1
            docker push $DOCKER_USER/hello-django:stable
            docker push $DOCKER_USER/hello-django:$CIRCLE_SHA1
            
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6.8
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run:
          name: Deploy to Server
          command: |
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
            ssh $SSH_USER@$SSH_HOST "
              cd ~/hello-django &&
              git pull &&
              ls &&
              docker-compose -f ./docker-compose.prod.yml pull &&
              docker-compose -f ./docker-compose.prod.yml up -d"

workflows:
  version: 2
  hello-django_pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - unit_tests:
          requires:
            - python_dependencies
      - build_docker_image:
          requires:
            - unit_tests
      - deploy:
          requires:
            - build_docker_image
